django/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^polls/', include('polls.urls', namespace='polls_ns')),
    url(r'^admin/', include(admin.site.urls)),
)

django/mysite/polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
    # e.g. /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # e.g. /polls/5
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # e.g. /polls/5/results
    url(r'^(?P<pk>\w+)/results/$', views.ResultsView.as_view(), name='results_url'),
    # e.g. /polls/5/vote
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),

)

django/mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    publication_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.publication_date > (timezone.now() - datetime.timedelta(days=1))

    # routines are implemented as objects and therefore have properties as well.
    was_published_recently.admin_order_field = 'publication_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Was published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django/mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from polls.models import Question, Choice


#def index(request):
#    """ Display the root page to of the URL .../polls/
#    :param request:
#    :return HttpResponse :
#    """
#    latest_question_list = Question.objects.order_by('-publication_date')[:5]

    # from django.template import RequestContext
    # from django.template import loader

    # template = loader.get_template('polls/index.html')
    # context_instance = RequestContext(request, {
    #     'latest_question_list' : latest_question_list,
    # })
    #output = '| '.join([p.question_text for p in latest_question_list])
    # return HttpResponse(template.render(context_instance))

#    context_params = { 'latest_question_list' : latest_question_list }
#    return render(request, 'polls/index.html', context_params)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        :return: the last five published questions.
        """
        return Question.objects.order_by('-publication_date')[:5]

'''
def detail(request, question_id):
    """ Display the detail of a particular question.
    :param request: HttpRequest
    :param question_id: Integer
    :return HttpResponse:
    """
    # return HttpResponse("You're looking at question, id=%s." % question_id)
#    try:
#        question = Question.objects.get(pk=question_id)
#    except Question.DoesNotExist:
#        raise Http404("Question does not exist!!")
#    return render(request, 'polls/detail.html', {'question' : question})

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question' : question})
'''

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    """ Handle the vote request.

    :param request:
    :param question_id:
    :return HttpResponse:
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            'polls/detail.html',
            {'question':question,
             'error_message':"You didn't select a choice.",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing with POST data. This prevents data from being
        # posted twice if a user hits the Back button.
        # Redirect to the 'result' page.
        return HttpResponseRedirect(reverse( 'polls_ns:results_url', args=(question.id,) ))
#        return HttpResponseRedirect(reverse( 'polls:results', args=(request.POST['csrfmiddlewaretoken'],) ))

django/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls_ns:vote' question.id %}" method="post">
    {% csrf_token %}

    {% for choice in question.choice_set.all %}
        <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
        </label>
        <br />
    {%  endfor %}
    <input type="submit" value="Vote" />
</form>

django/mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls_ns:detail' question.id %}">{{ question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
    {%  endfor %}
</ul>

<a href="{% url 'polls_ns:detail' question.id %}">Vote again??</a>